AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Resources:

  StopInstances:
    Type: 'AWS::Serverless::Function'
    Properties:
      Description: 'Stop on-demand instances or terminate spot instances that are not properly tagged (i.e. do not have autostop=false tag).'
      Handler: index.handler
      Runtime: nodejs8.10
      CodeUri: ./src
      MemorySize: 128
      Timeout: 60
      Events:
        Timer:
          Type: Schedule
          Properties:
            Schedule: rate(24 hours)
      Policies:
        - AWSLambdaExecute # Managed Policy
        - Version: '2012-10-17' # Policy Document
          Statement:
          - Effect: Allow
            Action:
              - 'ec2:DescribeInstances'
              - 'ec2:DescribeInstanceStatus'
              - 'ec2:DescribeTags'
              - 'ec2:StopInstances'
              - 'ec2:TerminateInstances'
              - 'ec2:CreateTags'
            Resource: '*'